src/Entity/Project.php
<?php

namespace App\Entity;

use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\ORM\Mapping as ORM;

/**
 * @ORM\Entity(repositoryClass="App\Repository\ProjectRepository")
 */
class Project
{
    /**
     * @ORM\Id()
     * @ORM\GeneratedValue()
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $urlName;

    /**
     * @ORM\Column(type="json_array")
     */
    private $name;

    /**
     * @ORM\Column(type="json_array")
     */
    private $headline;

    /**
     * @ORM\Column(type="string", length=255, nullable=true)
     */
    private $image;

    /**
     * @ORM\Column(type="string", length=255, nullable=true)
     */
    private $externalURL;

    /**
     * @ORM\Column(type="boolean")
     */
    private $redirectToExternal;

    /**
     * @ORM\Column(type="json_array", nullable=true)
     */
    private $about;

    /**
     * @ORM\Column(type="json_array", nullable=true)
     */
    private $modules;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $indicatorTranslationString;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $indicatorClass;

    /**
     * @ORM\Column(type="boolean")
     */
    private $visible;

    /**
     * @ORM\ManyToMany(targetEntity="App\Entity\PhotoAlbum", mappedBy="linkedProjects")
     */
    private $linkedPhotoAlbums;

    public function __construct()
    {
        $this->linkedPhotoAlbums = new ArrayCollection();
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getUrlName(): ?string
    {
        return $this->urlName;
    }

    public function setUrlName(string $urlName): self
    {
        $this->urlName = $urlName;

        return $this;
    }

    public function getName()
    {
        return $this->name;
    }

    public function setName($name): self
    {
        $this->name = $name;

        return $this;
    }

    public function getHeadline()
    {
        return $this->headline;
    }

    public function setHeadline($headline): self
    {
        $this->headline = $headline;

        return $this;
    }

    public function getImage(): ?string
    {
        if((substr($this->image, 0, 1) === "/")) {
            return "https://kevink.dev".$this->image;
        } else return $this->image;
    }

    public function getImageRaw(): ?string
    {
        return $this->image;
    }

    public function setImage(?string $image): self
    {
        $this->image = $image;

        return $this;
    }

    public function getExternalURL(): ?string
    {
        return $this->externalURL;
    }

    public function setExternalURL(?string $externalURL): self
    {
        $this->externalURL = $externalURL;

        return $this;
    }

    public function getRedirectToExternal(): ?bool
    {
        return $this->redirectToExternal;
    }

    public function setRedirectToExternal(bool $redirectToExternal): self
    {
        $this->redirectToExternal = $redirectToExternal;

        return $this;
    }

    public function getAbout()
    {
        return $this->about;
    }

    public function setAbout($about): self
    {
        $this->about = $about;

        return $this;
    }

    public function getModules()
    {
        return $this->modules;
    }

    public function setModules($modules): self
    {
        $this->modules = $modules;

        return $this;
    }

    public function getIndicatorTranslationString(): ?string
    {
        return $this->indicatorTranslationString;
    }

    public function setIndicatorTranslationString(string $indicatorTranslationString): self
    {
        $this->indicatorTranslationString = $indicatorTranslationString;

        return $this;
    }

    public function getIndicatorClass(): ?string
    {
        return $this->indicatorClass;
    }

    public function setIndicatorClass(string $indicatorClass): self
    {
        $this->indicatorClass = $indicatorClass;

        return $this;
    }

    public function getVisible(): ?bool
    {
        return $this->visible;
    }

    public function setVisible(bool $visible): self
    {
        $this->visible = $visible;

        return $this;
    }

    /**
     * @return Collection|PhotoAlbum[]
     */
    public function getLinkedPhotoAlbums(): Collection
    {
        return $this->linkedPhotoAlbums;
    }

    public function addLinkedPhotoAlbum(PhotoAlbum $linkedPhotoAlbum): self
    {
        if (!$this->linkedPhotoAlbums->contains($linkedPhotoAlbum)) {
            $this->linkedPhotoAlbums[] = $linkedPhotoAlbum;
            $linkedPhotoAlbum->addLinkedProject($this);
        }

        return $this;
    }

    public function removeLinkedPhotoAlbum(PhotoAlbum $linkedPhotoAlbum): self
    {
        if ($this->linkedPhotoAlbums->contains($linkedPhotoAlbum)) {
            $this->linkedPhotoAlbums->removeElement($linkedPhotoAlbum);
            $linkedPhotoAlbum->removeLinkedProject($this);
        }

        return $this;
    }
}

src/Controller/ProjectsController.php
<?php

namespace App\Controller;

use App\Entity\Project;
use App\Repository\ProjectRepository;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\RedirectResponse;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;

/**
 * Class ProjectsController
 * @package App\Controller
 * @Route("/projects")
 */
class ProjectsController extends AbstractController
{
    protected $projectsPerPage = 10;

    /**
     * @Route("/", defaults={"page": "1"}, name="projects")
     * @Route("/{page<[1-9]\d*>}", name="projectsPage")
     * @param ProjectRepository $projectRepository
     * @param int $page
     * @param Request $request
     * @param bool $isHome
     * @return Response
     */
    public function projectsPage(ProjectRepository $projectRepository, int $page, $isHome = false)
    {
        if($page == 1) {
            $isHome = true;
        }

        $offset = ($page - 1) * $this->projectsPerPage;

        $count = $projectRepository->count(["visible" => true]);
        $pageCount = ceil($count / $this->projectsPerPage);

        if($pageCount == 0) {
            $pageCount = 1;
        }

        if($page > $pageCount) {
            return $this->redirectToRoute("projectsPage",[
                "page" => $pageCount
            ]);
        }

        $projectList = $projectRepository->findVisibleProjects($this->projectsPerPage, $offset);

        return $this->render('projects/index.html.twig', [
            'module' => 'projects',
            'isHome' => $isHome,
            'projects' => $projectList,
            'pageCount' => $pageCount,
            'page' => $page
        ]);
    }

    /**
     * @Route("/view/{id<[0-9]\d*>}", name="projects_view_id")
     * @param Project $project
     * @return Response
     */
    public function viewProjectByID(Project $project)
    {
        return $this->redirectToRoute("projects_view", [
            "urlName" => $project->getUrlName()
        ]);
    }

    /**
     * @Route("/view/{urlName}", name="projects_view")
     * @param Project $project
     * @return Response
     */
    public function viewProject(Project $project)
    {

        if($project->getRedirectToExternal() == true) {
            return new RedirectResponse($project->getExternalURL());
        } else return $this->render('projects/view.html.twig', [
            'module' => 'projects',
            'project' => $project
        ]);
    }

    /**
     * @Route("/view/{urlName}/edit", name="projects_edit")
     * @param Project $project
     * @return Response
     */
    public function editProject(Project $project)
    {

        return $this->render('projects/edit.html.twig', [
            'module' => 'projects',
            'project' => $project
        ]);
    }
}

templates/projects/edit.html.twig
{% extends 'base.html.twig' %}

{% block title %}{% trans from "projects" %}project{% endtrans %}: {{ project.name|decodeLocaleArray|default("Unset") }}{% endblock %}

{% block stylesheets %}
    {{ parent() }}
    <link rel="stylesheet" href="{{ asset("assets/styles/editormd/editormd.min.css") }}" />
{% endblock %}

{% block javascripts %}
    {{ parent() }}


    <script src="{{ asset('assets/scripts/editormd/editormd.js') }}"></script>
    <script src="{{ asset('assets/scripts/editormd/languages/en.js') }}"></script>

    <script type="text/javascript">
        var contentEditor;

        function initEditor(md){
            contentEditor = editormd("editor", {
                width: "100%",
                height: 500,
                path : '{{ asset("assets/scripts/editormd/lib/") }}',
                theme : "dark",
                previewTheme : "light",
                editorTheme : "pastel-on-dark",
                markdown : md,
                codeFold : true,
                //syncScrolling : false,
                saveHTMLToTextarea : true,
                searchReplace : true,
                //watch : false,
                htmlDecode : "style,script,iframe|on*",
                //toolbar  : false,
                //previewCodeHighlight : false,
                emoji : true,
                taskList : true,
                tocm            : true,
                tex : true,
                flowChart : true,
                sequenceDiagram : true,
                //dialogLockScreen : false,
                //dialogShowMask : false,
                //dialogDraggable : false,
                //dialogMaskOpacity : 0.4,
                //dialogMaskBgColor : "#000",
                imageUpload : true,
                imageFormats : ["jpg", "jpeg", "gif", "png", "bmp", "webp"],
                imageUploadURL : "./php/upload.php",
                onload : function() {
                    console.log('onload', this);
                    //this.fullscreen();
                    //this.unwatch();
                    //this.watch().fullscreen();

                    //this.setMarkdown("#PHP");
                    //this.width("100%");
                    //this.height(480);
                    //this.resize("100%", 640);
                },
                onchange : contentChange
            });
        }
        
        function contentChange() {
            
        }

        {#var currentLang = "en";

        var contents = {{ post.content|json_encode()|raw }};
        var summaries = {{ post.summary|json_encode()|raw }};
        var titles = {{ post.title|json_encode()|raw }};

        if(contents == null) {
            contents = {};
        } else {
            contents = JSON.parse(contents);
        }
        if(summaries == null) {
            summaries = {};
        } else {
            summaries = JSON.parse(summaries);
        }
        if(titles == null) {
            titles = {};
        } else {
            titles = JSON.parse(titles);
        }

        function contentChange() {
            contents[currentLang] = contentEditor.getMarkdown();
            summaries[currentLang] = $("#summary").val();
            titles[currentLang] = $("#title").text();

            document.title = "Editor: "+titles[currentLang]+" | KevinK.dev";

            $("#edit_post_title").val(JSON.stringify(titles));
            $("#edit_post_summary").val(JSON.stringify(summaries));
            $("#edit_post_content").val(JSON.stringify(contents));
        }

        function switchLang(newLang) {
            var md = "Write here!";
            if(typeof contents[newLang] !== "undefined") {
                md = contents[newLang];
            }

            var summary = "Write here!";
            if(typeof summaries[newLang] !== "undefined") {
                summary = summaries[newLang];
            }

            var title = "Write here!";
            if(typeof titles[newLang] !== "undefined") {
                title = titles[newLang];
            }

            document.title = "Editor: "+title+" | KevinK.dev";

            contentEditor.setMarkdown(md);
            $("#summary").val(summary);
            $("#title").text(title);

            currentLang = newLang;
        }#}

        $("input[type=checkbox]").change(function (ev) {

        });

        function checkAllActive() {
            if(ev.currentTarget.checked) $(".projectAbout").addClass("active");
            else $(".projectAbout").removeClass("active");
        }

        $(function() {

            initEditor($("#editor").text());
        });
    </script>
{% endblock %}

{% block content %}
    <section class="projectHeader">
        <div>
            <div class="headerBackground" style="background-image: url({{ project.image|default("") }})"></div>
            <header>
                <div class="headerInner">
                    <h1>{% trans from "projects" %}project{% endtrans %}: {{ project.name|decodeLocaleArray|default("Unset") }}</h1>
                    <span class="postMeta">{{ project.headline|decodeLocaleArray|default("No headline set") }}</span>
                </div>
            </header>
            <div class="headerPlaceholder"></div>
        </div>
    </section>
        <section class="projectAbout">
            <article>
                <h1>{{ "about %project%"|trans({'%project%': project.name|decodeLocaleArray}, "projects") }} <input type="checkbox" {% if project.about|default(false) %}checked="checked"{% endif %}></h1>
                <div id="editor">{# project.about|decodeLocaleArray|markdown #}</div>
            </article>
        </section>
        <section class="projectDownloads">
            <div>
                <h1>{% trans from "projects" %}downloads{% endtrans %} <input type="checkbox" {% if project.modules.downloads|default(false) %}checked="checked"{% endif %}></h1>

                <table>
                    <tr><th>{% trans from "projects" %}version{% endtrans %}</th><th></th></tr>
                    {% for download in project.modules.downloads %}
                        <tr>
                            <td>{{ download.name }}</td>
                            <td>
                                <div class="downloadDropdown">
                                    <a href="javascript:void(0);">{% trans from "projects" %}download{% endtrans %}</a>
                                    <div class="dropdown">
                                        {% for link in download.links %}
                                            {% if link.type == "source" %}
                                                <a href="{{ link.url }}" target="_blank" title="{{ link.text|default("Source") }}"><i class="fas fa-file-archive"></i> {{ link.text|default("Source") }}</a>
                                            {% elseif link.type == "windows" %}
                                                <a href="{{ link.url }}" target="_blank" title="{{ link.text|default("Windows") }}"><i class="fab fa-windows"></i> {{ link.text|default("Windows") }}</a>
                                            {% elseif link.type == "linux" %}
                                                <a href="{{ link.url }}" target="_blank" title="{{ link.text|default("Linux") }}"><i class="fab fa-linux"></i> {{ link.text|default("Linux") }}</a>
                                            {% elseif link.type == "mac" %}
                                                <a href="{{ link.url }}" target="_blank" title="{{ link.text|default("Mac") }}"><i class="fab fa-apple"></i> {{ link.text|default("Mac") }}</a>
                                            {% else %}
                                                <a href="{{ link.url }}" target="_blank" title="{{ link.text|default("Unknown") }}"><i class="fas fa-file-download"></i> {{ link.text|default("Unknown") }}</a>
                                            {% endif %}
                                        {% endfor %}
                                    </div>
                                </div>
                            </td>
                        </tr>
                    {% endfor %}
                </table>
            </div>
        </section>
        <section class="projectLinks">
            <div>
                <h1>{% trans from "projects" %}links{% endtrans %} <input type="checkbox" {% if project.modules.links|default(false) %}checked="checked"{% endif %}></h1>
                <div class="linkList" style="display: block">
                    {% for link in project.modules.links %}
                        <div class="projectLink">
                            <select class="projectLinkType">
                                <option value="github" {% if link.type == "github" %}selected{% endif %}>GitHub</option>
                                <option value="gitlab" {% if link.type == "gitlab" %}selected{% endif %}>GitLab</option>
                                <option value="git" {% if link.type == "git" %}selected{% endif %}>Git</option>
                                <option value="bitbucket" {% if link.type == "bitbucket" %}selected{% endif %}>Bitbucket</option>
                                <option value="custom" {% if link.type == "custom" %}selected{% endif %}>Custom</option>
                            </select>
                            <input type="url" value="{{ link.url|default("") }}" class="projectLinkURL">
                            <input type="checkbox" {% if link.text|default(false) %}checked="checked"{% endif %}><input type="text" value="{{ link.text|default("") }}" class="customLabel">
                        </div><br>
                    {% endfor %}
                </div>
            </div>
        </section>
{% endblock %}

templates/projects/index.html.twig
{% extends 'base.html.twig' %}

{% block title %}{% trans from "modules" %}projects{% endtrans %}{% endblock %}

{% block content %}
    <section class="projectsSection">
        <article>
            <h1>{% trans from "modules" %}projects{% endtrans %}</h1>
            {% if not isHome %}
                <h2>{{ "page %page%/%pageCount%"|trans({'%page%': page, '%pageCount%': pageCount}, "blog") }}</h2>
            {% else %}
                {% trans from "projects" %}projectsHomeText{% endtrans %}
            {% endif %}

            {% include 'projects/projectList.html.twig' with { "projects": projects } %}

            <div class="pageButtons">
                {% if page - 1 > 0 %}<a href="{{ path("projectsPage", {"page": (page - 1)}) }}">&lt;</a>{% endif %}
                <div class="flexSpacer">{{ "page %page%/%pageCount%"|trans({'%page%': page, '%pageCount%': pageCount}, "blog") }}</div>
                {% if page + 1 < pageCount %}<a href="{{ path("projectsPage", {"page": (page + 1)}) }}">&gt;</a>{% endif %}
            </div>
        </article>
    </section>
    <a class="section hireMeSection" target="_blank" rel="noopener" href="mailto:kevin@kevink.dev">
        <div>
            <span>{% trans from "projects" %}hireMe{% endtrans %}</span>
            <i class="fas fa-fw fa-chevron-right"></i>
        </div>
    </a>
    <a class="section hireMeSection spf-link" href="{{ path("friends_index") }}">
        <div>
            <span>{% trans %}moreByFriends{% endtrans %}</span>
            <i class="fas fa-fw fa-chevron-right"></i>
        </div>
    </a>
{% endblock %}

templates/projects/projectCard.html.twig
<div class="projectCard tagPHP tagCSS tagHTML tagJavaScript">
    <div class="projectCardActivityIndicator {{ project.indicatorClass }}">{{ project.indicatorTranslationString|trans([], "projects") }}</div>
    <div class="projectCardImage lazy" data-bg="url({{ asset(project.imageRaw) | imagine_filter("cardThumb") }})"></div>{#TODO: Add Low-Res version to always load#}
    <div class="projectCardMeta">
        <span class="projectCardTitle">{{ project.name|decodeLocaleArray }}</span>
        <span class="projectCardTeaser">{{ project.headline|decodeLocaleArray }}</span>
    </div>
    <div class="projectCardCTAContainer">
        {% if not project.redirectToExternal %}<div class="projectCardCTA"><a href="{{ path('projects_view', {"urlName": project.urlName}) }}" class="spf-link">{% trans from "projects" %}view{% endtrans %}</a></div>{% endif %}
        {% if project.externalURL %}<div class="projectCardCTA"><a href="{{ project.externalURL }}" target="_blank"><i class="fas fa-external-link-alt"></i> {% trans from "projects" %}viewexternal{% endtrans %}</a></div>{% endif %}
    </div>
</div>

{#<div class="projectCard tagPHP tagCSS tagHTML tagJavaScript">
    <div class="projectCardActivityIndicator activityIndicatorBlue">{% trans from "projects" %}statusLive{% endtrans %}</div>
    <div class="projectCardImage" style="background-image: url('{{ asset('assets/images/mario-caruso-770233-unsplash.jpg') }}');"></div>
    <div class="projectCardMeta">
        <span class="projectCardTitle">KevinK.dev</span>
        <span class="projectCardTeaser">This site</span>
    </div>
    <div class="projectCardCTA"><a href="" class="spf-link">{% trans from "projects" %}view{% endtrans %}</a></div>
    <div class="projectCardCTA"><a href=""><i class="fas fa-external-link-alt"></i> {% trans from "projects" %}viewexternal{% endtrans %}</a></div>
</div>

    <div class="projectCardActivityIndicator activityIndicatorGreen">Work in Progress</div>
    <div class="projectCardActivityIndicator activityIndicatorYellow">On Hold</div>
    <div class="projectCardActivityIndicator activityIndicatorRed">Cancelled</div>
#}

templates/projects/projectList.html.twig
<div class="projectList">
    {% for project in projects %}
        {% include 'projects/projectCard.html.twig' with { "project": project } %}
    {% endfor %}

    {% if projects|length == 0 %}
        <h4>{% trans from "projects" %}noProjects{% endtrans %}</h4>
    {% endif %}


</div>

templates/projects/view.html.twig
{% extends 'base.html.twig' %}

{% block title %}{% trans from "projects" %}project{% endtrans %}: {{ project.name|decodeLocaleArray }}{% endblock %}

{% block content %}
    <section class="projectHeader">
        <div>
            <div class="headerBackground lazy" data-bg="url({{ asset(project.imageRaw) | imagine_filter("w1920") }})"></div>{#TODO: Add Low-Res version to always load#}
            <header>
                <div class="headerInner">
                    <h1>{% trans from "projects" %}project{% endtrans %}: {{ project.name|decodeLocaleArray }}</h1>
                    <span class="postMeta">{{ project.headline|decodeLocaleArray }}</span>
                </div>
            </header>
            <div class="headerPlaceholder"></div>
        </div>
    </section>
    {% if project.about|default(false) %}
        <section class="projectAbout">
            <article>
                <h1>{{ "about %project%"|trans({'%project%': project.name|decodeLocaleArray}, "projects") }}</h1>
                {{ project.about|decodeLocaleArray|markdown }}
            </article>
        </section>
    {% endif %}
    {% if project.modules.downloads|default(false) %}
        <section class="projectDownloads">
            <div>
                <h1>{% trans from "projects" %}downloads{% endtrans %}</h1>

                <table>
                    <tr><th>{% trans from "projects" %}version{% endtrans %}</th><th></th></tr>
                    {% for download in project.modules.downloads %}
                        <tr>
                            <td>{{ download.name }}</td>
                            <td>
                                <div class="downloadDropdown">
                                    <a href="javascript:void(0);">{% trans from "projects" %}download{% endtrans %}</a>
                                    <div class="dropdown">
                                        {% for link in download.links %}
                                            {% if link.type == "source" %}
                                                <a href="{{ link.url }}" target="_blank" title="{{ link.text|default("Source") }}"><i class="fas fa-file-archive"></i> {{ link.text|default("Source") }}</a>
                                            {% elseif link.type == "windows" %}
                                                <a href="{{ link.url }}" target="_blank" title="{{ link.text|default("Windows") }}"><i class="fab fa-windows"></i> {{ link.text|default("Windows") }}</a>
                                            {% elseif link.type == "linux" %}
                                                <a href="{{ link.url }}" target="_blank" title="{{ link.text|default("Linux") }}"><i class="fab fa-linux"></i> {{ link.text|default("Linux") }}</a>
                                            {% elseif link.type == "mac" %}
                                                <a href="{{ link.url }}" target="_blank" title="{{ link.text|default("Mac") }}"><i class="fab fa-apple"></i> {{ link.text|default("Mac") }}</a>
                                            {% else %}
                                                <a href="{{ link.url }}" target="_blank" title="{{ link.text|default("Unknown") }}"><i class="fas fa-file-download"></i> {{ link.text|default("Unknown") }}</a>
                                            {% endif %}
                                        {% endfor %}
                                    </div>
                                </div>
                            </td>
                        </tr>
                    {% endfor %}
                </table>
            </div>
        </section>
    {% endif %}
    {% if project.modules.links|default(false) or project.externalURL|default(false) %}
        <section class="projectLinks">
            <div>
                <h1>{% trans from "projects" %}links{% endtrans %}</h1>
                <div class="linkList">
                    {% for link in project.modules.links|default([]) %}
                        {% if link.type == "github" %}
                            <a href="{{ link.url }}" target="_blank"><i class="fab fa-github"></i> {% trans from "projects" %}viewGitHub{% endtrans %}</a>
                        {% elseif link.type == "gitlab" %}
                            <a href="{{ link.url }}" target="_blank"><i class="fab fa-gitlab"></i> {% trans from "projects" %}viewGitLab{% endtrans %}</a>
                        {% elseif link.type == "git" %}
                            <a href="{{ link.url }}" target="_blank"><i class="fab fa-git"></i> {% trans from "projects" %}viewGitRepo{% endtrans %}</a>
                        {% elseif link.type == "bitbucket" %}
                            <a href="{{ link.url }}" target="_blank"><i class="fab fa-bitbucket"></i> {% trans from "projects" %}viewBitBucket{% endtrans %}</a>
                        {% else %}
                            <a href="{{ link.url }}" target="_blank"><i class="fas fa-external-link-alt"></i> {{ link.text }}</a>
                        {% endif %}
                    {% endfor %}

                    {% if project.externalURL %}
                        <a href="{{ project.externalURL }}" target="_blank"><i class="fas fa-external-link-alt"></i> {% trans from "projects" %}viewExternal{% endtrans %}</a>
                    {% endif %}
                </div>
            </div>
        </section>
        <a class="section hireMeSection" target="_blank" rel="noopener" href="mailto:kevin@kevink.dev">
            <div>
                <span>{% trans from "projects" %}hireMe{% endtrans %}</span>
                <i class="fas fa-fw fa-chevron-right"></i>
            </div>
        </a>
    {% endif %}
{% endblock %}