src/Entity/BlogPost.php
<?php

namespace App\Entity;

use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\ORM\Mapping as ORM;

/**
 * @ORM\Entity(repositoryClass="App\Repository\BlogPostRepository")
 */
class BlogPost
{
    /**
     * @ORM\Id()
     * @ORM\GeneratedValue()
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\Column(type="json_array")
     */
    private $title;

    /**
     * @ORM\Column(type="json_array")
     */
    private $content;

    /**
     * @ORM\ManyToOne(targetEntity="App\Entity\BlogCategory", inversedBy="posts")
     * @ORM\JoinColumn(nullable=false)
     */
    private $category;

    /**
     * @ORM\ManyToMany(targetEntity="App\Entity\BlogTag", inversedBy="posts")
     */
    private $tags;

    /**
     * @ORM\ManyToOne(targetEntity="App\Entity\User", inversedBy="blogPosts")
     * @ORM\JoinColumn(nullable=false)
     */
    private $author;

    /**
     * @ORM\Column(type="json_array")
     */
    private $summary;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $image;

    /**
     * @ORM\Column(type="datetime")
     */
    private $publishTime;

    /**
     * @ORM\Column(type="boolean")
     */
    private $visible;

    /**
     * @ORM\ManyToMany(targetEntity="App\Entity\PhotoAlbum", mappedBy="linkedBlogPosts")
     */
    private $linkedPhotoAlbums;

    public function __construct()
    {
        $this->tags = new ArrayCollection();
        $this->linkedPhotoAlbums = new ArrayCollection();
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getTitle()
    {
        return $this->title;
    }

    public function setTitle($title): self
    {
        $this->title = $title;

        return $this;
    }

    public function getContent()
    {
        return $this->content;
    }

    public function setContent($content): self
    {
        $this->content = $content;

        return $this;
    }

    public function getCategory(): ?BlogCategory
    {
        return $this->category;
    }

    public function setCategory(?BlogCategory $category): self
    {
        $this->category = $category;

        return $this;
    }

    /**
     * @return Collection|BlogTag[]
     */
    public function getTags(): Collection
    {
        return $this->tags;
    }

    public function addTag(BlogTag $tag): self
    {
        if (!$this->tags->contains($tag)) {
            $this->tags[] = $tag;
        }

        return $this;
    }

    public function removeTag(BlogTag $tag): self
    {
        if ($this->tags->contains($tag)) {
            $this->tags->removeElement($tag);
        }

        return $this;
    }

    public function getAuthor(): ?User
    {
        return $this->author;
    }

    public function setAuthor(?User $author): self
    {
        $this->author = $author;

        return $this;
    }

    public function getSummary()
    {
        return $this->summary;
    }

    public function setSummary($summary): self
    {
        $this->summary = $summary;

        return $this;
    }

    public function getImage(): ?string
    {
        if((substr($this->image, 0, 1) === "/")) {
            return "https://kevink.dev".$this->image;
        } else return $this->image;
    }

    public function getImageRaw(): ?string
    {
        return $this->image;
    }

    public function setImage(string $image): self
    {
        $this->image = $image;

        return $this;
    }

    public function getPublishTime(): ?\DateTimeInterface
    {
        return $this->publishTime;
    }

    public function setPublishTime(\DateTimeInterface $publishTime): self
    {
        $this->publishTime = $publishTime;

        return $this;
    }

    public function getVisible(): ?bool
    {
        return $this->visible;
    }

    public function setVisible(bool $visible): self
    {
        $this->visible = $visible;

        return $this;
    }


    public function getCanonicalName(): string {
        // Swap out Non "Letters" with a -
        $text = preg_replace('/[^\\pL\d]+/u', '-', $this->getTitle());

        // Trim out extra -'s
        $text = trim($text, '-');

        // Convert letters that we have left to the closest ASCII representation
        $text = iconv('utf-8', 'us-ascii//TRANSLIT', $text);

        // Make text lowercase
        $text = strtolower($text);

        // Strip out anything we haven't been able to convert
        $text = preg_replace('/[^-\w]+/', '', $text);

        return $text;
    }

    /**
     * @return Collection|PhotoAlbum[]
     */
    public function getLinkedPhotoAlbums(): Collection
    {
        return $this->linkedPhotoAlbums;
    }

    public function addLinkedPhotoAlbum(PhotoAlbum $linkedPhotoAlbum): self
    {
        if (!$this->linkedPhotoAlbums->contains($linkedPhotoAlbum)) {
            $this->linkedPhotoAlbums[] = $linkedPhotoAlbum;
            $linkedPhotoAlbum->addLinkedBlogPost($this);
        }

        return $this;
    }

    public function removeLinkedPhotoAlbum(PhotoAlbum $linkedPhotoAlbum): self
    {
        if ($this->linkedPhotoAlbums->contains($linkedPhotoAlbum)) {
            $this->linkedPhotoAlbums->removeElement($linkedPhotoAlbum);
            $linkedPhotoAlbum->removeLinkedBlogPost($this);
        }

        return $this;
    }
}

src/Entity/User.php
<?php

namespace App\Entity;

use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\ORM\Mapping as ORM;
use Symfony\Component\Security\Core\User\UserInterface;

/**
 * @ORM\Entity(repositoryClass="App\Repository\UserRepository")
 */
class User implements UserInterface
{
    /**
     * @ORM\Id()
     * @ORM\GeneratedValue()
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\Column(type="string", length=180, unique=true)
     */
    private $email;

    /**
     * @ORM\Column(type="json")
     */
    private $roles = [];

    /**
     * @var string The hashed password
     * @ORM\Column(type="string")
     */
    private $password;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $Username;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $PublicName;

    /**
     * @ORM\OneToMany(targetEntity="App\Entity\BlogPost", mappedBy="author")
     */
    private $blogPosts;

    public function __construct()
    {
        $this->blogPosts = new ArrayCollection();
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getEmail(): ?string
    {
        return $this->email;
    }

    public function setEmail(string $email): self
    {
        $this->email = $email;

        return $this;
    }

    /**
     * A visual identifier that represents this user.
     *
     * @see UserInterface
     */
    public function getUsername(): string
    {
        return (string) $this->Username;
    }

    /**
     * @see UserInterface
     */
    public function getRoles(): array
    {
        $roles = $this->roles;
        // guarantee every user at least has ROLE_USER
        $roles[] = 'ROLE_USER';

        return array_unique($roles);
    }

    public function setRoles(array $roles): self
    {
        $this->roles = $roles;

        return $this;
    }

    /**
     * @see UserInterface
     */
    public function getPassword(): string
    {
        return (string) $this->password;
    }

    public function setPassword(string $password): self
    {
        $this->password = $password;

        return $this;
    }

    /**
     * @see UserInterface
     */
    public function getSalt()
    {
        // not needed when using the "bcrypt" algorithm in security.yaml
    }

    /**
     * @see UserInterface
     */
    public function eraseCredentials()
    {
        // If you store any temporary, sensitive data on the user, clear it here
        // $this->plainPassword = null;
    }

    public function setUsername(string $Username): self
    {
        $this->Username = $Username;

        return $this;
    }

    public function getPublicName(): ?string
    {
        return $this->PublicName;
    }

    public function setPublicName(string $PublicName): self
    {
        $this->PublicName = $PublicName;

        return $this;
    }

    /**
     * @return Collection|BlogPost[]
     */
    public function getBlogPosts(): Collection
    {
        return $this->blogPosts;
    }

    public function addBlogPost(BlogPost $blogPost): self
    {
        if (!$this->blogPosts->contains($blogPost)) {
            $this->blogPosts[] = $blogPost;
            $blogPost->setAuthor($this);
        }

        return $this;
    }

    public function removeBlogPost(BlogPost $blogPost): self
    {
        if ($this->blogPosts->contains($blogPost)) {
            $this->blogPosts->removeElement($blogPost);
            // set the owning side to null (unless already changed)
            if ($blogPost->getAuthor() === $this) {
                $blogPost->setAuthor(null);
            }
        }

        return $this;
    }

    public function __toString()
    {
        return $this->getPublicName();
    }
}

src/Controller/BlogController.php
<?php

namespace App\Controller;

use App\Entity\BlogCategory;
use App\Entity\BlogPost;
use App\Form\EditPostType;
use App\Repository\BlogPostRepository;
use App\Utils\Localize;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\HttpKernel\Exception\NotFoundHttpException;
use Symfony\Component\Routing\Annotation\Route;

/**
 * Class BlogController
 * @package App\Controller
 * @Route("/blog")
 */
class BlogController extends AbstractController
{
    protected $postsPerPage = 10;
    private $localize;

    public function __construct()
    {
        $this->localize = new Localize();
    }

    /**
     * @Route("/", defaults={"page": "1"}, name="blogHome")
     * @Route("/{page<[0-9]\d*>}", name="blogPage")
     * @param BlogPostRepository $blogPostRepository
     * @param int $page
     * @param Request $request
     * @param bool $isHome
     * @return Response
     */
    public function blogPage(BlogPostRepository $blogPostRepository, int $page, Request $request, $isHome = false) {
        $offset = ($page - 1) * $this->postsPerPage;

        if($offset < 0) {
            $offset = 0;
        }

        $count = $blogPostRepository->count(["visible" => true]);
        $pageCount = ceil($count / $this->postsPerPage);

        if($page > $pageCount) {
            return $this->redirectToRoute("blogPage",[
                "page" => $pageCount
            ]);
        }

        $postList = $blogPostRepository->findVisiblePosts($this->postsPerPage, $offset);

        foreach ($postList as $key => $post) {
            $postList[$key] = $this->localize->getLocalizedContent($post, $request->getLocale());
        }

        return $this->render('blog/index.html.twig', [
            'module' => 'blog',
            'isHome' => $isHome,
            'posts' => $postList,
            'pageCount' => $pageCount,
            'page' => $page
        ]);
    }

    /**
     * @Route("/read/{post_id}", name="blogViewDirect", defaults={"year": "0", "month": "0", "day": "0", "canonical": "aaaaa"})
     * @Route("/{year}/{month}/{day}/{post_id}-{canonical}", name="blogView")
     * @param Request $request
     * @param BlogPostRepository $blogPostRepository
     * @param $year
     * @param $month
     * @param $day
     * @param $post_id
     * @param $canonical
     * @return Response
     */
    public function blogView(Request $request, BlogPostRepository $blogPostRepository, $year, $month, $day, $post_id, $canonical) {
        $post = $blogPostRepository->findOneBy([
            "id" => $post_id
        ]);

        $post = $this->localize->getLocalizedContent($post, $request->getLocale());

        $canonicalGen = $post->getCanonicalName();

        if(date("Y/m/d", $post->getPublishTime()->getTimestamp()) != sprintf("%s/%s/%s", $year, $month, $day) || $canonicalGen != $canonical) {
            return $this->redirectToRoute("blogView", [
               "post_id" => $post_id,
                "day" =>  date("d", $post->getPublishTime()->getTimestamp()),
                "month" =>  date("m", $post->getPublishTime()->getTimestamp()),
                "year" =>  date("Y", $post->getPublishTime()->getTimestamp()),
                "canonical" => $canonicalGen
            ]);
        }

        return $this->render('blog/read.html.twig', [
           'module' => 'blog',
           'post' => $post
        ]);
    }

    /**
     * @Route("/category/{urlName}", name="blogCategory", defaults={"page": "1"})
     * @Route("/category/{urlName}/{page}", name="blogCategoryPage")
     * @param BlogCategory $category
     * @param int $page
     * @param Request $request
     * @return Response
     */
    public function blogCategoryPage(BlogCategory $category, int $page, Request $request) {
        $offset = ($page - 1) * $this->postsPerPage;

        $postRepository = $this->getDoctrine()->getRepository(BlogPost::class);

        $count = $postRepository->count(["visible" => true, "category" => $category]);
        $pageCount = ceil($count / $this->postsPerPage);

        $postList = $postRepository->findVisiblePostsByCategory($category, $this->postsPerPage, $offset);

        foreach ($postList as $key => $post) {
            $postList[$key] = $this->localize->getLocalizedContent($post, $request->getLocale());
        }


        return $this->render('blog/category.html.twig', [
            'module' => 'blog',
            'posts' => $postList,
            'pageCount' => $pageCount,
            'page' => $page,
            'category' => $category
        ]);
    }

    /**
     * @Route("/editor/new", name="blogPostNew", defaults={"postID": "-1"})
     * @Route("/editor/edit/{postID}", name="blogPostEdit")
     * @param BlogPostRepository $blogPostRepository
     * @param Request $request
     * @param int $postID
     * @return Response
     */
    public function blogPostEditor(BlogPostRepository $blogPostRepository, Request $request, int $postID) {
        $this->denyAccessUnlessGranted("ROLE_ADMIN");

        $form = $this->createForm(EditPostType::class);


        if($postID == -1) {
            $post = new BlogPost();
            $post->setAuthor($this->getUser());
            $post->setPublishTime(new \DateTime());
        } else {
            $post = $blogPostRepository->findOneBy([
                "id" => $postID
            ]);
            if($post == null) {
                throw new NotFoundHttpException();
            }
        }

        $post->setTitle(json_encode($post->getTitle()));
        $post->setSummary(json_encode($post->getSummary()));
        $post->setContent(json_encode($post->getContent()));

        $form->setData($post);

        $form->handleRequest($request);

        $entityManager = $this->getDoctrine()->getManager();

        if ($form->isSubmitted() && $form->isValid()) {
            $post = $form->getData();

            $post->setTitle(json_decode($post->getTitle(), true));
            $post->setSummary(json_decode($post->getSummary(), true));
            $post->setContent(json_decode($post->getContent(), true));

            $entityManager->persist($post);
            $entityManager->flush();

            return $this->redirectToRoute("blogViewDirect", ["post_id" => $post->getId()]);
        }


        return $this->render('blog/editor.html.twig', [
            'module' => 'blog',
            'post' => $post,
            'form' => $form->createView()
        ]);
    }
}

templates/blog/category.html.twig
{% extends 'base.html.twig' %}

{% block title %}Blog{% endblock %}

{% block content %}
    <section class="blogSection">
        <article>
            <h1>{% trans from "blog" %}category{% endtrans %}: {{ category.languageKey|trans({}, "blog") }}</h1>
            <h2>{{ "page %page%/%pageCount%"|trans({'%page%': page, '%pageCount%': pageCount}, "blog") }}</h2>
            {{ category.descriptionLanguageKey|trans({}, "blog") }}

            {% include 'blog/postList.html.twig' with { "posts": posts } %}

            <div class="pageButtons">
                {% if page - 1 > 0 %}<a href="{{ path("blogCategoryPage", {"urlName": category.urlName,"page": (page - 1)}) }}">&lt;</a>{% endif %}
                <div class="flexSpacer">{{ "page %page%/%pageCount%"|trans({'%page%': page, '%pageCount%': pageCount}, "blog") }}</div>
                {% if page + 1 < pageCount %}<a href="{{ path("blogCategoryPage", {"urlName": category.urlName, "page": (page + 1)}) }}">&gt;</a>{% endif %}
            </div>
        </article>
    </section>
{% endblock %}

templates/blog/editor.html.twig
{% extends 'base.html.twig' %}

{% if post.category %}
    {% set categoryName = post.category.languageKey|trans({}, "blog") %}
{% else %}
    {% set categoryName = "chooseCategory"|trans({}, "blog") %}
{% endif %}

{% block title %}Editor{% endblock %}

{% block stylesheets %}
    {{ parent() }}
    <link rel="stylesheet" href="{{ asset('assets/styles/multiLanguageEditor.css') }}">
{% endblock %}

{% block javascripts %}
    {{ parent() }}

    <script src="{{ asset('assets/scripts/multiLanguageEditor.js') }}"></script>

    <script>
        multiLanguageEditor.initialize("#edit_post_title");
        multiLanguageEditor.initializeTextArea("#edit_post_content");
        multiLanguageEditor.initialize("#edit_post_summary");
    </script>
{% endblock %}

{% block content %}
    <section class="postContent postEditor">
        <article>
            <!--<div class="multiLanguageEditorInline" data-input="multiLanguageBox1">
                <input placeholder="Title">
                <div class="multiLanguageSwitcherTrigger">+</div>
                <div class="multiLanguageSwitcher">
                    <div class="multiLanguageChooserBox">
                        <span data-langtag="en" class="active"><span>en</span><span class="multiLanguageChooserRemove">&times;</span></span>
                        <span data-langtag="de" class="inactive"><span>de</span><span class="multiLanguageChooserRemove">&times;</span></span>
                        <span data-langtag="*" class="inactive"><span>*</span><span class="multiLanguageChooserRemove">&times;</span></span>
                    </div>
                </div>
            </div>-->

            <h1>Edit Post</h1>

            {{ form_start(form) }}
                {{ form_row(form.title) }}
                {{ form_row(form.summary) }}
                {{ form_row(form.content) }}
                {{ form_row(form.publishTime) }}
                {{ form_row(form.image) }}
                {{ form_row(form.author) }}
                {{ form_row(form.tags) }}
                {{ form_row(form.category) }}
                {{ form_row(form.visible) }}

                <button class="btn">{% trans %}save{% endtrans %}</button>
            {{ form_end(form) }}
        </article>

    </section>
{% endblock %}

templates/blog/editor_old.html.twig
{% extends 'base.html.twig' %}

{% if post.category %}
    {% set categoryName = post.category.languageKey|trans({}, "blog") %}
{% else %}
    {% set categoryName = "chooseCategory"|trans({}, "blog") %}
{% endif %}

{% block title %}Editor loading...{% endblock %}

{% block stylesheets %}
    {{ parent() }}
    <link rel="stylesheet" href="{{ asset("assets/styles/editormd/editormd.min.css") }}" />
{% endblock %}

{% block javascripts %}
    {{ parent() }}


    <script src="{{ asset('assets/scripts/editormd/editormd.js') }}"></script>
    <script src="{{ asset('assets/scripts/editormd/languages/en.js') }}"></script>

    <script type="text/javascript">
        var contentEditor;

        function initEditor(md){
            contentEditor = editormd("editor", {
                width: "100%",
                height: 500,
                path : '{{ asset("assets/scripts/editormd/lib/") }}',
                theme : "dark",
                previewTheme : "light",
                editorTheme : "pastel-on-dark",
                markdown : md,
                codeFold : true,
                //syncScrolling : false,
                saveHTMLToTextarea : true,
                searchReplace : true,
                //watch : false,
                htmlDecode : "style,script,iframe|on*",
                //toolbar  : false,
                //previewCodeHighlight : false,
                emoji : true,
                taskList : true,
                tocm            : true,
                tex : true,
                flowChart : true,
                sequenceDiagram : true,
                //dialogLockScreen : false,
                //dialogShowMask : false,
                //dialogDraggable : false,
                //dialogMaskOpacity : 0.4,
                //dialogMaskBgColor : "#000",
                imageUpload : true,
                imageFormats : ["jpg", "jpeg", "gif", "png", "bmp", "webp"],
                imageUploadURL : "./php/upload.php",
                onload : function() {
                    console.log('onload', this);
                    //this.fullscreen();
                    //this.unwatch();
                    //this.watch().fullscreen();

                    //this.setMarkdown("#PHP");
                    //this.width("100%");
                    //this.height(480);
                    //this.resize("100%", 640);
                    switchLang($("#languageSwitch").val());
                },
                onchange : contentChange
            });
        }

        var currentLang = "en";

        var contents = {{ post.content|json_encode()|raw }};
        var summaries = {{ post.summary|json_encode()|raw }};
        var titles = {{ post.title|json_encode()|raw }};

        if(contents == null) {
            contents = {};
        } else {
            contents = JSON.parse(contents);
        }
        if(summaries == null) {
            summaries = {};
        } else {
            summaries = JSON.parse(summaries);
        }
        if(titles == null) {
            titles = {};
        } else {
            titles = JSON.parse(titles);
        }

        function contentChange() {
            contents[currentLang] = contentEditor.getMarkdown();
            summaries[currentLang] = $("#summary").val();
            titles[currentLang] = $("#title").text();

            document.title = "Editor: "+titles[currentLang]+" | KevinK.dev";

            $("#edit_post_title").val(JSON.stringify(titles));
            $("#edit_post_summary").val(JSON.stringify(summaries));
            $("#edit_post_content").val(JSON.stringify(contents));
        }

        function switchLang(newLang) {
            var md = "Write here!";
            if(typeof contents[newLang] !== "undefined") {
                md = contents[newLang];
            }

            var summary = "Write here!";
            if(typeof summaries[newLang] !== "undefined") {
                summary = summaries[newLang];
            }

            var title = "Write here!";
            if(typeof titles[newLang] !== "undefined") {
                title = titles[newLang];
            }

            document.title = "Editor: "+title+" | KevinK.dev";

            contentEditor.setMarkdown(md);
            $("#summary").val(summary);
            $("#title").text(title);

            currentLang = newLang;
        }

        $(function() {

            initEditor($("#editor").text());

            $("#goto-line-btn").bind("click", function(){
                contentEditor.gotoLine(90);
            });

            $("#show-btn").bind('click', function(){
                contentEditor.show();
            });

            $("#hide-btn").bind('click', function(){
                contentEditor.hide();
            });

            $("#get-md-btn").bind('click', function(){
                alert(contentEditor.getMarkdown());
            });

            $("#get-html-btn").bind('click', function() {
                alert(contentEditor.getHTML());
            });

            $("#watch-btn").bind('click', function() {
                contentEditor.watch();
            });

            $("#unwatch-btn").bind('click', function() {
                contentEditor.unwatch();
            });

            $("#preview-btn").bind('click', function() {
                contentEditor.previewing();
            });

            $("#fullscreen-btn").bind('click', function() {
                contentEditor.fullscreen();
            });

            $("#show-toolbar-btn").bind('click', function() {
                contentEditor.showToolbar();
            });

            $("#close-toolbar-btn").bind('click', function() {
                contentEditor.hideToolbar();
            });

            $("#toc-menu-btn").click(function(){
                contentEditor.config({
                    tocDropdown   : true,
                    tocTitle      : "TOC",
                });
            });

            $("#toc-default-btn").click(function() {
                contentEditor.config("tocDropdown", false);
            });

            $("#summary").change(contentChange);

            $("#title").keyup(contentChange);

            $("#languageSwitch").change(function () {
                switchLang($("#languageSwitch").val());
            });
        });
    </script>
{% endblock %}

{% block content %}
    <section class="postContent postEditor">
        <article>
            <div class="headerBackground" style="background-image: url({{ post.image|default(asset("assets/images/mario-caruso-770233-unsplash.jpg")) }})"></div>
            <header>
                <div class="headerInner">
                    <h1 contenteditable="true" id="title">Loading...</h1>
                    <span class="postMeta">{{ "by %author% on %publishdate% in %categorylink%"|trans({'%author%': post.author.publicName, '%publishdate%': "XX.XX.XXXX", '%categorylink%': categoryName}, "blog")|raw }}</span>
                </div>
            </header>
            <div class="headerPlaceholder"></div>

            <select id="languageSwitch">
                <option value="en" selected>English</option>
                <option value="de">Deutsch</option>
            </select>

            <div class="contentEditor" id="editor">Editor loading...</div>

            <div class="contentSummary">
                <h1>Summary</h1>
                <textarea id="summary" style="width: 100%"></textarea>
            </div>

            <h1>Meta</h1>

            {{ form_start(form) }}
                {{ form_row(form.publishTime) }}
                {{ form_row(form.image) }}
                {{ form_row(form.author) }}
                {{ form_row(form.tags) }}
                {{ form_row(form.category) }}
                {{ form_row(form.visible) }}

                <button class="btn">{% trans %}save{% endtrans %}</button>
            {{ form_end(form) }}
        </article>

    </section>
{% endblock %}

templates/blog/postList.html.twig
<div class="postList">
    {% for post in posts %}
        {% include 'postcard.html.twig' with { "postTitle": post.title, "teaserText": post.summary, "link": path("blogView", {"year": post.publishTime|date("Y"), "month": post.publishTime|date("m"), "day": post.publishTime|date("d"), "post_id": post.id, "canonical": post.canonicalName}), "postImage": post.imageRaw } %}
    {% endfor %}

    {% if posts|length == 0 %}
        <h4>{% trans from "blog" %}noPosts{% endtrans %}</h4>
    {% endif %}
</div>

templates/blog/read.html.twig
{% extends 'base.html.twig' %}

{% set categoryName = post.category.languageKey|trans({}, "blog") %}
{% set categoryLink = path("blogCategory", {"urlName": post.category.urlName}) %}

{% block meta %}

    <meta name="description" content="{{ post.summary }}">
    <meta name="author" content="{{ post.author.publicName }}">
    <meta property="og:url" content="https://kevink.dev{{ path("blogView", {"year": post.publishTime|date("Y"), "month": post.publishTime|date("m"), "day": post.publishTime|date("d"), "post_id": post.id, "canonical": post.canonicalName}) }}" />
    <meta property="article:published_time" content="{{ post.publishTime|date("Y-m-d") }}T{{ post.publishTime|date("G:i:sP") }}" />
    <meta property="og:image" content="{{ post.image }}" />
    <meta name="twitter:card" content="summary_large_image" />
    <meta name="twitter:image:src" content="{{ post.image }}" />
    <meta name="og:title" content="{{ post.title }}" />
    <meta name="twitter:text:title" content="{{ post.title }}" />
    <meta name="twitter:title" content="{{ post.title }}" />
    <script type="application/ld+json">
        {
            "@context": "https://schema.org",
            "@type": "NewsArticle",
            "mainEntityOfPage": {
                "@type": "WebPage",
                "@id": "https://google.com/article"
            },
            "headline": "{{ post.title }}",
            "image": [
                "{{ post.image }}"
            ],
            "datePublished": "{{ post.publishTime|date("Y-m-d") }}T{{ post.publishTime|date("G:i:sP") }}",
            "author": {
                "@type": "Person",
                "name": "{{ post.author.publicName }}"
            },
            "publisher": {
                "@type": "Organization",
                "name": "KevinK.dev",
                "logo": {
                    "@type": "ImageObject",
                    "url": "{{ asset('assets/images/logo/roundedbglogo.png') }}"
                }
            },
            "description": "{{ post.summary }}"
        }
    </script>

{% endblock %}

{% block canonical %}
    <link rel="canonical" href="https://kevink.dev{{ path("blogViewDirect", { "post_id": post.id }) }}"/>

{% endblock %}

{% block title %}{{ post.title|raw }}{% endblock %}

{% block content %}
    <section class="postContent">
        <article>
            <div class="headerBackground lazy" data-bg="url({{ asset(post.imageRaw) | imagine_filter("w1920") }})"></div>{#TODO: Add Low-Res version to always load#}
            <header>
                <div class="headerInner">
                    <h1>{{ post.title }}</h1>
                    <span class="postMeta">{{ "by %author% on %publishdate% in %categorylink%"|trans({'%author%': post.author.publicName, '%publishdate%': post.publishTime|date("d.m.Y"), '%categorylink%': '<a href="'~categoryLink~'" class="spf-link">'~categoryName~'</a>'}, "blog")|raw }}</span>
                </div>
            </header>
            <div class="headerPlaceholder"></div>

            {{ post.content|markdown }}
        </article>
    </section>
{% endblock %}